name: flutter_figma
description: Rendering Figma components as Flutter widgets.
version: 0.2.0-alpha.1
homepage: https://github.com/aloisdeniel/figma-to-flutter/tree/master/figma_theme_generator

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  recase: ^4.0.0
  path: ^1.8.0
  path_provider: ^2.0.2
  collection: ^1.15.0
  figma: ^3.0.0
  path_drawing: ^0.5.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter: